### ISSUE TITLE
Add scenario(s) for object search

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/xk6-neofs#90]
* see https://github.com/nspcc-dev/neofs-node/pull/2892

there are no scenarios to test object search. It is proposed to add ones. To start, actions from the mentioned node optimization may be used:
1. (preset) create 1 container
2. (preset) place N objects into it
3. send Q empty (`*`) search queries

---

* keep an eye on #86

**Comment by EESergey** [comment]
Here's an example of how it could work:
xk6-neofs run grpc.js -e GRPC_ENDPOINTS=host1,host2 -e SEARCHERS=3 -e ITERATIONS=100 -e PREGEN_JSON=file.json

What results do we need to get:
data.metrics.neofs_obj_search_total.values.rate
data.metrics.neofs_obj_search_duration.values.avg
data.metrics.neofs_obj_search_duration.values.p(95)
